image: golang:latest

before_script:
  - mkdir -p $GOPATH/src/git.onebytedata.com/$CI_PROJECT_NAMESPACE
  - cd $GOPATH/src/git.onebytedata.com/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

stages:
  - test
  - build
  - publish
  - deploy

variables:
  GIT_STRATEGY: clone
  GO111MODULE: "on"
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  TAG_BUILD: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}
  TAG_RELEASE: $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}

test:
  stage: test
  script:
    - echo $SSH_SETUP | base64 --decode | bash
