image: golang:latest

before_script:
  - mkdir -p $GOPATH/src/git.onebytedata.com/$CI_PROJECT_NAMESPACE
  - cd $GOPATH/src/git.onebytedata.com/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

stages:
  - test
  - build
  - publish
  - deploy

variables:
  GIT_STRATEGY: clone
  GO111MODULE: "on"
  LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  TAG_BUILD: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}
  TAG_RELEASE: $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}

test:
  stage: test
  script:
    - echo $SSH_SETUP | base64 --decode | bash
    - go test ./...

build:
  stage: build
  script:
    - echo $SSH_SETUP | base64 --decode | bash
    - CGO_ENABLED="0" GOOS=linux GOARCH=amd64 go build -v -a -ldflags "-X main.version=build.${CI_PIPELINE_ID}" -o build/docker/obd-dicom
    - GOOS=linux GOARCH=amd64 go build -v -a -ldflags "-X main.version=build.${CI_PIPELINE_ID}" -o build/linux/obd-dicom
    - GOOS=darwin GOARCH=amd64 go build -v -a -ldflags "-X main.version=build.${CI_PIPELINE_ID}" -o build/macos/obd-dicom
    - GOOS=windows GOARCH=amd64 go build -v -a -ldflags "-X main.version=build.${CI_PIPELINE_ID}" -o build/windows/obd-dicom.exe
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - build
  artifacts:
    paths:
      - build/linux/obd-dicom
      - build/macos/obd-dicom
      - build/windows/obd-dicom.exe
    expire_in: 30 days

publish-build:
  image: docker:19-dind
  stage: publish
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:19-dind
  only:
    - master
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - build
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $LATEST_IMAGE -t $TAG_BUILD .
    - docker push $LATEST_IMAGE
    - docker push $TAG_BUILD

publish-release:
  image: docker:19-dind
  stage: publish
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:19-dind
  only:
    - tags
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - build
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $LATEST_IMAGE -t $TAG_RELEASE .
    - docker push $LATEST_IMAGE
    - docker push $TAG_RELEASE
